name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 12 点运行一次
  workflow_dispatch: # 手动触发支持

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "GAODBK"
          git config --global user.email "2758034192@qq.com"

      - name: Add Upstream
        run: git remote add upstream https://github.com/fanmingming/live.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: git merge upstream/main --allow-unrelated-histories || true

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
